from pathlib import Path
p=Path('index.html')
s=p.read_text()
start=s.index('async function renderRecap(){')
end=s.index('function completedRecordGames()', start)
new=r'''function renderRecap(){const current=+state.league?.season||0,h=state.history.find(x=>+x.season===current);let done=(h?.weeks||[]).filter(x=>+x.week<week()&&group(x.matchups||[]).length&&x.matchups.some(m=>(+m.points||0)>0)).sort((a,b)=>b.week-a.week)[0];if(!done&&state.last?.length&&group(state.last).length)done={week:Math.max(1,week()-1),matchups:state.last};if(!done){$('recapScores').innerHTML='<div class="empty">No completed prior week found yet.</div>';return}const gs=group(done.matchups||[]),rw=$('recapWeekNo');if(rw)rw.textContent=done.week;$('recapScores').innerHTML=gs.map(p=>{const a=state.rosters.find(r=>r.roster_id===p[0].roster_id),b=state.rosters.find(r=>r.roster_id===p[1].roster_id);return`<div class="match"><div class="row"><b>${esc(teamName(a))}</b><b>${(+p[0].points||0).toFixed(1)}</b></div><div class="row"><b>${esc(teamName(b))}</b><b>${(+p[1].points||0).toFixed(1)}</b></div></div>`}).join('')||'<div class="empty">No final scores found.</div>';const winners=gs.map(p=>(+p[0].points||0)>=(+p[1].points||0)?p[0]:p[1]),losers=gs.map(p=>(+p[0].points||0)<(+p[1].points||0)?p[0]:p[1]),top=[...(done.matchups||[])].sort((a,b)=>(+b.points||0)-(+a.points||0))[0],tr=state.rosters.find(r=>r.roster_id===top?.roster_id),mw=[...winners].sort((a,b)=>(+b.points||0)-(+a.points||0))[0],mr=state.rosters.find(r=>r.roster_id===mw?.roster_id),low=[...losers].sort((a,b)=>(+a.points||0)-(+b.points||0))[0],lr=state.rosters.find(r=>r.roster_id===low?.roster_id);$('recapHeadline').textContent=tr?`${teamName(tr)} set the Week ${done.week} pace`:`Week ${done.week} complete`;$('recapHeadlineNote').textContent=top?`${(+top.points||0).toFixed(1)} points led the league.`:'';$('managerWeek').textContent=mr?teamName(mr):'—';$('managerWeekNote').textContent=mw?`${(+mw.points||0).toFixed(1)} points in a win — highest-scoring winning performance.`:'';$('loserWeek').textContent=lr?teamName(lr):'—';$('loserWeekNote').textContent=low?`${(+low.points||0).toFixed(1)} points — lowest-scoring losing performance.`:''}'''
s=s[:start]+new+s[end:]
s=s.replace('historyEvent();await renderRecap();renderManagers();','historyEvent();renderRecap();renderManagers();',1)
p.write_text(s)
print('recap uses already-loaded current-season history')
